# Verify the accuracy of TDVP1 against exact diagonalization.
#
# Experimental finding (bond dimension large enough to represent the evolved state,
# Krylov tolerances far below any physical scale): the sweeps reproduce exp(-i·H·dt)
# exactly — the error sits at machine precision and is INDEPENDENT of dt. The algorithm
# carries no time-discretization error at all (stronger than a second-order splitting);
# the only error channel is the MPS-manifold truncation when D cannot hold the
# entanglement generated by the evolution (also dt-independent).
using LinearAlgebra, Random
using FiniteMPSAlgorithms

include(joinpath(@__DIR__, "..", "test", "helpers.jl"))

function tdvp_error(H, Hd, ψ0, T, dt, D)
    nsteps = round(Int, T / dt)
    ψ = changebond!(copy(ψ0); D)
    env = DMRGCache(H, ψ)
    alg = TDVP1(stepsize=dt, verbosity=0)
    for _ in 1:nsteps
        sweep!(env, alg)
    end
    ψ_ed = exp(Matrix(-im * Hd * T)) * todense(ψ0)
    return norm(todense(env.ket) - ψ_ed) / norm(ψ_ed)
end

function scan(L, D; T=1.0, dts=[0.2, 0.1, 0.05, 0.025, 0.0125])
    Random.seed!(2024)
    p = model_params(L)
    H = mpo_model(p)
    Hd = dense_model(p)
    ψ0 = normalize!(randommps(ComplexF64, fill(2, L); D=8))

    println("TDVP1 vs ED: L = $L, D = $D, T = $T, ‖H‖ = ", round(opnorm(Hd), digits=3))
    println("dt          error")
    for dt in dts
        err = tdvp_error(H, Hd, ψ0, T, dt, D)
        println("$(rpad(dt, 12))", err)
    end
end

# bond dimension large enough for the exact evolution: machine-precision agreement
scan(4, 32)
scan(6, 32)

# critical bond dimension (D = 4 = max Schmidt rank of a d=2, L=4 state): still exact
scan(4, 4; dts=[0.2, 0.1, 0.05, 0.025])

# too small: the error is dominated by the MPS-manifold truncation, not by dt
scan(6, 2; dts=[0.2, 0.1, 0.05, 0.025])
